const DATA = [
    {
        id: 1,
        name: 'Лапша с креветкой в сливочном соусе',
        price: 55000,
        image: '/images/menu/1.png',
        category: 'noodles',
        isTop: true,
    },
    {
        id: 2,
        name: 'Лапша с морепродуктами',
        price: 55000,
        image: '/images/menu/2.png',
        category: 'noodles',
    },
    {
        id: 3,
        name: 'Копченая лапша с курицей',
        price: 50000,
        image: '/images/menu/3.png',
        category: 'noodles',
    },
    {
        id: 4,
        name: 'Гречневая лапша собо',
        price: 50000,
        image: '/images/menu/4.png',
        category: 'noodles',
    },
    {
        id: 5,
        name: 'Лапша с говядиной',
        price: 45000,
        image: '/images/menu/5.png',
        category: 'noodles',
    },
    {
        id: 6,
        name: 'Лапша с курицей',
        price: 40000,
        image: '/images/menu/6.jpg',
        category: 'noodles',
    },
    {
        id: 7,
        name: 'Сяки тяхан',
        price: 50000,
        image: '/images/menu/7.png',
        category: 'fried_rice',
    },
    {
        id: 8,
        name: 'Говядина от шефа',
        price: 50000,
        image: '/images/menu/8.png',
        category: 'hot_dishes',
    },
    {
        id: 9,
        name: 'Оякодон',
        price: 45000,
        image: '/images/menu/9.png',
        category: 'hot_dishes',
    },
    {
        id: 10,
        name: 'Кацу карри',
        price: 45000,
        image: '/images/menu/10.png',
        category: 'hot_dishes',
    },
    {
        id: 11,
        name: 'Кацу дон',
        price: 40000,
        image: '/images/menu/11.png',
        category: 'hot_dishes',
    },
    {
        id: 12,
        name: 'Рисовая лапша с морепродуктами',
        price: 120000,
        image: '/images/menu/104.png',
        category: 'hot_dishes',
        isTop: true,
    },
    {
        id: 13,
        name: 'Сяки тяхан',
        price: 50000,
        image: '/images/menu/13.png',
        category: 'hot_dishes',
    },
    {
        id: 14,
        name: 'Том кха',
        price: 45000,
        image: '/images/menu/112.png',
        category: 'soups',
    },
    {
        id: 15,
        name: 'Том ям',
        price: 75000,
        image: '/images/menu/112.png',
        category: 'soups',
        isTop: true,
    },
    {
        id: 16,
        name: 'Тори рамен',
        price: 50000,
        image: '/images/menu/105.png',
        category: 'soups',
    },
    {
        id: 17,
        name: 'Рисовая лапша с морепродуктами',
        price: 120000,
        image: '/images/menu/104.png',
        category: 'soups',
    },
    {
        id: 19,
        name: 'Кранч с ласосом',
        price: 65000,
        image: '/images/menu/18.png',
        category: 'rolls',
    },
    {
        id: 20,
        name: 'Кранч',
        price: 45000,
        image: '/images/menu/19.png',
        category: 'rolls',
    },
    {
        id: 21,
        name: 'Запеченный с угрем',
        price: 75000,
        image: '/images/menu/20.png',
        category: 'rolls',
    },
    {
        id: 22,
        name: 'Спайс',
        price: 50000,
        image: '/images/menu/21.png',
        category: 'rolls',
    },
    {
        id: 23,
        name: 'Эбифрай',
        price: 85000,
        image: '/images/menu/22.png',
        category: 'rolls',
    },
    {
        id: 24,
        name: 'Запеченные роллы с курицей',
        price: 45000,
        image: '/images/menu/23.png',
        category: 'rolls',
    },
    {
        id: 25,
        name: 'Запеченные роллы с ласосем',
        price: 65000,
        image: '/images/menu/24.png',
        category: 'rolls',
    },
    {
        id: 26,
        name: 'Запеченные роллы с креветкой',
        price: 65000,
        image: '/images/menu/25.png',
        category: 'rolls',
    },
    {
        id: 27,
        name: 'Запеченные роллы с мидиями',
        price: 60000,
        image: '/images/menu/26.png',
        category: 'rolls',
    },
    {
        id: 28,
        name: 'Запеченные роллы с кальмаром',
        price: 60000,
        image: '/images/menu/27.png',
        category: 'rolls',
    },
    {
        id: 29,
        name: 'Запеченные роллы с тунцом',
        price: 65000,
        image: '/images/menu/28.png',
        category: 'rolls',
    },
    {
        id: 30,
        name: 'Паттайя',
        price: 70000,
        image: '/images/menu/29.png',
        category: 'rolls',
    },
    {
        id: 31,
        name: 'Киота',
        price: 65000,
        image: '/images/menu/131.png',
        category: 'rolls',
    },
    {
        id: 32,
        name: 'Сибуя',
        price: 125000,
        image: '/images/menu/132.jpg',
        category: 'rolls',
        isTop: true,
    },
    {
        id: 33,
        name: 'Каваи',
        price: 75000,
        image: '/images/menu/134.jpg',
        category: 'rolls',
    },
    {
        id: 34,
        name: 'Чесночный хлеб',
        price: 15000,
        image: '/images/menu/33.png',
        category: 'snacks',
    },
    {
        id: 35,
        name: 'Спринг роллы с курицей в соусе карри',
        price: 25000,
        image: '/images/menu/34.png',
        category: 'snacks',
    },
    {
        id: 36,
        name: 'Шарики с ласосем, креветкой и крабом',
        price: 30000,
        image: '/images/menu/35.png',
        category: 'snacks',
    },
    {
        id: 37,
        name: 'Куриные стрипсы',
        price: 30000,
        image: '/images/menu/36.png',
        category: 'snacks',
    },
    {
        id: 38,
        name: 'Сырные подушки',
        price: 35000,
        image: '/images/menu/37.png',
        category: 'snacks',
    },
    {
        id: 39,
        name: 'Картофель по деревенски со стрипсами',
        price: 35000,
        image: '/images/menu/38.png',
        category: 'snacks',
    },
    {
        id: 40,
        name: 'Картофель по деревенски',
        price: 20000,
        image: '/images/menu/39.png',
        category: 'snacks',
    },
    {
        id: 41,
        name: 'Картофель фри',
        price: 20000,
        image: '/images/menu/40.png',
        category: 'snacks',
    },
    {
        id: 42,
        name: 'Смайлик картошка',
        price: 20000,
        image: '/images/menu/41.png',
        category: 'snacks',
    },
    {
        id: 43,
        name: 'Запеченный мидии',
        price: 65000,
        image: '/images/menu/42.png',
        category: 'snacks',
    },
    {
        id: 44,
        name: 'Туна Лайт',
        price: 90000,
        image: '/images/menu/43.png',
        category: 'cold_rolls',
    },
    {
        id: 45,
        name: 'Эби Лайт',
        price: 90000,
        image: '/images/menu/44.png',
        category: 'cold_rolls',
    },
    {
        id: 46,
        name: 'Филадельфия с креветкой',
        price: 110000,
        image: '/images/menu/45.png',
        category: 'cold_rolls',
    },
    {
        id: 47,
        name: 'Филадельфия кунжут',
        price: 55000,
        image: '/images/menu/46.png',
        category: 'cold_rolls',
    },
    {
        id: 48,
        name: 'Фудзияма',
        price: 55000,
        image: '/images/menu/90.png',
        category: 'cold_rolls',
    },
    {
        id: 49,
        name: 'Филадельфия в огурце',
        price: 55000,
        image: '/images/menu/47.png',
        category: 'cold_rolls',
    },
    {
        id: 50,
        name: 'Калифорния с креветкой',
        price: 90000,
        image: '/images/menu/48.png',
        category: 'cold_rolls',
    },
    {
        id: 51,
        name: 'Хосомаки с ласосем',
        price: 40000,
        image: '/images/menu/49.png',
        category: 'cold_rolls',
    },
    {
        id: 52,
        name: 'Аризона с угрем',
        price: 60000,
        image: '/images/menu/50.png',
        category: 'cold_rolls',
    },
    {
        id: 53,
        name: 'Гинза',
        price: 100000,
        image: '/images/menu/51.png',
        category: 'cold_rolls',
    },
    {
        id: 54,
        name: 'Унаги урамаки',
        price: 100000,
        image: '/images/menu/52.png',
        category: 'cold_rolls',
    },
    {
        id: 55,
        name: 'Калифорния с авокадо',
        price: 80000,
        image: '/images/menu/53.png',
        category: 'cold_rolls',
    },
    {
        id: 56,
        name: 'Хосомаки с угрем',
        price: 40000,
        image: '/images/menu/54.png',
        category: 'cold_rolls',
    },
    {
        id: 57,
        name: 'Сияке маки',
        price: 40000,
        image: '/images/menu/55.png',
        category: 'cold_rolls',
    },
    {
        id: 58,
        name: 'Филадельфия лайт',
        price: 60000,
        image: '/images/menu/56.png',
        category: 'cold_rolls',
    },
    {
        id: 59,
        name: 'Филка авокадо',
        price: 90000,
        image: '/images/menu/57.png',
        category: 'cold_rolls',
    },
    {
        id: 60,
        name: 'Радуга',
        price: 90000,
        image: '/images/menu/58.png',
        category: 'cold_rolls',
    },
    {
        id: 61,
        name: 'Филадельфия классическая',
        price: 85000,
        image: '/images/menu/59.png',
        category: 'cold_rolls',
    },
    {
        id: 62,
        name: 'Green Chili Roll',
        price: 45000,
        image: '/images/menu/60.png',
        category: 'cold_rolls',
    },
    {
        id: 63,
        name: 'Канада',
        price: 120000,
        image: '/images/menu/130.jpg',
        category: 'cold_rolls',
    },
    //salads
    {
        id: 64,
        name: 'Хрустящие баклажаны',
        price: 45000,
        image: '/images/menu/62.png',
        category: 'salads',
    },
    {
        id: 65,
        name: 'Салат копченый лосось',
        price: 50000,
        image: '/images/menu/63.png',
        category: 'salads',
    },
    {
        id: 66,
        name: 'Японский салат цезарь',
        price: 55000,
        image: '/images/menu/64.png',
        category: 'salads',
    },
    {
        id: 67,
        name: 'Цезарь классический',
        price: 45000,
        image: '/images/menu/65.png',
        category: 'salads',
    },
    {
        id: 68,
        name: 'Салат Тигер круинч',
        price: 95000,
        image: '/images/menu/66.png',
        category: 'salads',
    },
    //sushis
    {
        id: 69,
        name: '3 Спайси суши с лососем',
        price: 45000,
        image: '/images/menu/67.png',
        category: 'sushis',
    },
    {
        id: 70,
        name: '3 Суши с лососем',
        price: 45000,
        image: '/images/menu/68.png',
        category: 'sushis',
    },
    {
        id: 71,
        name: 'Спайси суши',
        price: 75000,
        image: '/images/menu/69.png',
        category: 'sushis',
    },
    {
        id: 72,
        name: '3 Нигири с угрем',
        price: 60000,
        image: '/images/menu/70.png',
        category: 'sushis',
    },
    {
        id: 73,
        name: 'Сет нигири тунец, креветка, лосось, угорь',
        price: 72000,
        image: '/images/menu/71.png',
        category: 'sushis',
    },
    // КОФЕ (отдельная категория)
    {
        id: 74,
        name: 'Cappuccino 0.2',
        price: 20000,
        image: '/images/menu/74.png',
        category: 'coffee',
    },
    {
        id: 75,
        name: 'Cappuccino 0.3',
        price: 25000,
        image: '/images/menu/75.png',
        category: 'coffee',
    },
    {
        id: 76,
        name: 'ICE Cappuccino 0.5',
        price: 30000,
        image: '/images/menu/76.png',
        category: 'coffee',
    },
    {
        id: 77,
        name: 'Latte 0.2',
        price: 20000,
        image: '/images/menu/77.png',
        category: 'coffee',
    },
    {
        id: 78,
        name: 'Latte 0.3',
        price: 25000,
        image: '/images/menu/78.png',
        category: 'coffee',
    },
    {
        id: 79,
        name: 'ICE Latte 0.5',
        price: 30000,
        image: '/images/menu/79.png',
        category: 'coffee',
    },
    {
        id: 80,
        name: 'Americano 0.2',
        price: 15000,
        image: '/images/menu/80.png',
        category: 'coffee',
    },
    {
        id: 81,
        name: 'Americano 0.3',
        price: 20000,
        image: '/images/menu/81.png',
        category: 'coffee',
    },
    {
        id: 82,
        name: 'ICE Americano 0.5',
        price: 25000,
        image: '/images/menu/82.png',
        category: 'coffee',
    },
    // НАПИТКИ (безалкогольные, кроме кофе)
    {
        id: 83,
        name: 'Glisse 0.4',
        price: 30000,
        image: '/images/menu/83.png',
        category: 'drinks',
    },
    {
        id: 84,
        name: 'Maxito 0.5',
        price: 30000,
        image: '/images/menu/84.png',
        category: 'drinks',
    },
    {
        id: 85,
        name: 'Maxito Grafin 1.5',
        price: 80000,
        image: '/images/menu/85.png',
        category: 'drinks',
    },
    {
        id: 86,
        name: 'Milkshake 0.4',
        price: 35000,
        image: '/images/menu/86.png',
        category: 'drinks',
    },
    {
        id: 87,
        name: 'Fresh 0.3',
        price: 35000,
        image: '/images/menu/87.png',
        category: 'drinks',
    },
    {
        id: 88,
        name: 'Smoothie 0.4',
        price: 35000,
        image: '/images/menu/88.png',
        category: 'drinks',
    },
    {
        id: 89,
        name: 'ICE Tea 0.4',
        price: 25000,
        image: '/images/menu/89.png',
        category: 'drinks',
    },
    //Чай
    {
        id: 90,
        name: 'Цветочный чай',
        price: 20000,
        image: '/images/menu/92.png',
        category: 'tea',
    },
    {
        id: 91,
        name: 'Каркаде',
        price: 30000,
        image: '/images/menu/93.png',
        category: 'tea',
    },
    {
        id: 92,
        name: 'Зеленый чай',
        price: 20000,
        image: '/images/menu/94.png',
        category: 'tea',
    },
    {
        id: 93,
        name: 'Молочный улун',
        price: 20000,
        image: '/images/menu/95.png',
        category: 'tea',
    },
    {
        id: 94,
        name: 'Чай с лимоном',
        price: 25000,
        image: '/images/menu/96.png',
        category: 'tea',
    },
    {
        id: 95,
        name: 'Манго',
        price: 35000,
        image: '/images/menu/97.png',
        category: 'tea',
    },
    {
        id: 96,
        name: 'Маракуй',
        price: 35000,
        image: '/images/menu/98.png',
        category: 'tea',
    },
    {
        id: 97,
        name: 'Чай черный',
        price: 20000,
        image: '/images/menu/99.png',
        category: 'tea',
    },
    {
        id: 98,
        name: 'Чай леcные ягоды',
        price: 35000,
        image: '/images/menu/100.png',
        category: 'tea',
    },
    {
        id: 99,
        name: 'Чай клюквенный',
        price: 35000,
        image: '/images/menu/101.png',
        category: 'tea',
    },
    {
        id: 100,
        name: 'Чай малиновый',
        price: 35000,
        image: '/images/menu/102.png',
        category: 'tea',
    },
    {
        id: 101,
        name: 'Чай клубничный',
        price: 35000,
        image: '/images/menu/103.png',
        category: 'tea',
    },
    // Аукционные блюда
    {
        id: 102,
        name: 'Сет на двоих',
        price: 175000,
        image: '/images/menu/110.jpg',
        category: 'promo',
    },
    {
        id: 103,
        name: 'Сет Салмон',
        price: 180000,
        image: '/images/menu/111.png',
        category: 'promo',
    },
    {
        id: 104,
        name: 'Сет Аригато',
        price: 150000,
        image: '/images/menu/113.jpg',
        category: 'promo',
    },
    {
        id: 105,
        name: 'Сет студенческий (40)',
        price: 220000,
        image: '/images/menu/109.png',
        category: 'promo',
    },
    {
        id: 106,
        name: 'Сет запечённый',
        price: 150000,
        image: '/images/menu/107.png',
        category: 'promo',
    },
    {
        id: 107,
        name: 'Сет Love is',
        price: 220000,
        image: '/images/menu/108.png',
        category: 'promo',
    },
    // Сет
    {
        id: 108,
        name: 'Сет Ёнг',
        price: 220000,
        image: '/images/menu/120.png',
        category: 'sets',
    },
    {
        id: 109,
        name: 'Сет фьюжен',
        price: 220000,
        image: '/images/menu/121.png',
        category: 'sets',
    },
    {
        id: 110,
        name: 'Сет Хот Сан',
        price: 175000,
        image: '/images/menu/122.png',
        category: 'sets',
    },
    {
        id: 111,
        name: 'Сет Хйоужун',
        price: 330000,
        image: '/images/menu/123.png',
        category: 'sets',
    },
    {
        id: 112,
        name: 'Сет Лонг го',
        price: 350000,
        image: '/images/menu/124.png',
        category: 'sets',
    },
    {
        id: 113,
        name: 'Сет Аниме',
        price: 335000,
        image: '/images/menu/125.png',
        category: 'sets',
    },
    {
        id: 114,
        name: 'Сет Окинава',
        price: 220000,
        image: '/images/menu/126.png',
        category: 'sets',
    },
    {
        id: 115,
        name: 'Сет для всех ',
        price: 330000,
        image: '/images/menu/127.png',
        category: 'sets',
    },
];

export default DATA;